config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'about', to: 'welcome#about'
  resources :articles
  get 'signup', to:'users#new'
  resources :users, except: [:new]

  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user

  validates :title, presence:true, length: {minimun: 5, maximum: 20}
  validates :description, presence:true, length: {minimun: 20, maximum: 150}
  validates :user_id, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord

  has_many :articles, dependent: :destroy

  before_save { self.email = email.downcase }

  validates :username, length: { minimun: 3, maximum: 25 },
            presence: true, uniqueness: { case_sensitive: false }


  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
             uniqueness: { case_sensitive: false },
             length: { maximum: 105 }, presence: true

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must logged in to preform this action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only:  [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    #debugger
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was created successfully"
      redirect_to article_path(@article)
    else
      render 'new'
    end

  end

  def show
  end

  def edit
    #debugger
    @article.user = current_user
  end

  def update

    if @article.update(article_params)
      flash[:success] = "Article was created successfully"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Article deleted successfully'
    redirect_to articles_path
  end


  private
    def find_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

    def require_same_user

        if current_user != @article.user && !current_user.admin?
          flash[:danger] = "You can only edit or update your own articles"
          redirect_to root_path
        end

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    #debugger
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = " successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Something went wrong"
      render 'new'
    end
  end

  def destroy
    #debugger
    user = User.find_by(id: session[:user_id])
    session[:user_id] = nil
    flash[:success] = "#{user.username} is logged out"
    redirect_to root_path
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :destroy, :update, :edit]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Fred Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def Show

  end

  def edit

  end

  def update

    if @user.update(user_params)
      flash[:success] = "#{@user.username} was updated with success"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

def destroy

  @user.destroy
  flash[:danger] = "#{@user.username} was successfully deleted and his/her articles"
  redirect_to users_path
end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def find_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:danger] = "You can only edit, update your own account"
        redirect_to root_path
      end
    end

    def require_admin
      if !logged_in? && !current_user.admin?
        flash[:danger] = "Only admin can perform this action"
        redirect_to root_path
      end
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to articles_path if logged_in?
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 88 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt:user.username, class: "rounded-circle")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Author</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% obj.each do |art| %>
    <tr>
      <td><%= art.title%></td>
      <td><%= truncate(art.description, length: 50)%></td>
      <div class="article-meta-details">
        <td><small>Created by: <%= art.user.username.capitalize if art.user %><br>
                   <%= time_ago_in_words(art.created_at) %> <br>
                   last updated: <%= time_ago_in_words(art.updated_at) %></small></td>
      </div>
      <% if logged_in? && (current_user == art.user || current_user.admin?) %>
          <td><%= link_to 'Edit', edit_article_path(art.id),class:'btn btn-outline-primary' %>
              <%= link_to 'Show',article_path(art.id), class:'btn btn-outline-success'%>

              <%= link_to 'Delete', article_path(art),class:'btn btn-outline-danger',
            method: :delete, data: {confirm: 'are you sure you want to delete:'} %><br></td>

      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<div class='row'>
  <div class='col-lg'>
    <%= form_for @article do |f| %>
      <div class='form-group'>
        <div class='control-label  col-sm-2'>
          <%= f.label :Title  %>
        </div>
        <div class='col-sm-8'>
          <%= f.text_field :title, class:"form-control",
           placeholder: "title of article", autofocus: true %>
        </div>
      </div>
      <div class='form-group'>
        <div class='control-label col-sm-8'>
          <%= f.label :Description  %>
        </div>
        <div class='col-sm-8'>
          <%= f.text_area :description, rows:10, class:'form-control',
          placeholder:'body of article' %>
        </div>
      </div>

      <div class='form-group'>
        <div class='col-offset-2 col-sm-10'>
          <%= f.submit "Create", class:'btn btn-primary btn-lg'  %>
        </div>
      </div>


<% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align='center'> Edit your article </h1>

  <%= render 'shared/flash', obj: @article %>

<%= render 'form'%>

<p align='center'>[ <%= link_to 'Cancel editing the article', articles_path %> ]</p>

app/views/articles/index.html.erb
<%= render "article", obj: @articles %>

app/views/articles/new.html.erb
<h1 align='center'> Create an article </h1>
  <%= render 'shared/flash', obj: @article %>
<%= render 'articles/form'%>

app/views/articles/show.html.erb
<h2 align='center'>Title: <%= @article.title %></h2>

  <h4><strong>Description:</strong></h4>
    <hr>
    <%= @article.description %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}"%> alert-dismissible fade show' role="alert">
    <ul>
      <li><%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-dark bg-dark">
<%= link_to 'Fred Blog', root_path, class:"navbar-brand", id:"logo" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Articles', articles_path, class:"navbar-brand", id:"logo" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown,"
          role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a><%= link_to 'New article', new_article_path, class:"dropdown-item" %></a>
            <a class="dropdown-item" href="#">########</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">########</a>
          </div>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Users', users_path, class:"nav-link enabled" %>
        <!--<a class="nav-link disabled" href="#" tabindex="-1"
         aria-disabled="true">Users</a>-->
      </li>
    </ul>
<form class="form-inline">
  <% if logged_in? %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown, profit"
          role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your Profile <%= "Admin" if current_user.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a><%= link_to 'Edit your profile', edit_user_path(current_user), class:"dropdown-item" %></a>
            <a><%= link_to 'View your profile', user_path(current_user), class:"dropdown-item" %></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
    </div>
     <button class="btn btn-info my-2 my-sm-0" type="submit">
     <%= link_to'Logout', logout_path, method: :delete, id:"log" %></button>
  <% else %>
      <button class="btn btn-info my-2 my-sm-0" type="submit">
      <%= link_to'Log in', login_path, id:"log" %></button>
  <% end %>
 </form>
</div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>

    <title>FredBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/nav' %><br>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

  </body>
</html>

app/views/shared/_flash.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <%= pluralize(obj.errors.count, 'error') %>
    Prohibited this article from being saved:
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li>
          <%= message %><br>
        </li>
        <% end %>
      </div>
    </ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/flash', obj: @user %>

<div class='row'>
  <div class='col-lg'>
    <%= form_for @user do |f| %>
      <div class='form-group'>
        <div class='control-label  col-sm-2'>
          <%= f.label :Username  %>
        </div>
        <div class='col-sm-8'>
          <%= f.text_field :username, class:"form-control",
           placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class='form-group'>
        <div class='control-label col-sm-8'>
          <%= f.label :email  %>
        </div>
        <div class='col-sm-8'>
          <%= f.email_field :email, rows:10, class:'form-control',
          placeholder:'Enter your email address' %>
        </div>
      </div>
      <div class='form-group'>
        <div class='control-label col-sm-8'>
          <%= f.label :Password  %>
        </div>
        <div class='col-sm-8'>
          <%= f.password_field :password, rows:10, class:'form-control',
          placeholder:'Enter your Password' %>
        </div>
      </div>

      <div class='form-group'>
        <div class='col-offset-2 col-sm-10'>
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account",
            class:'btn btn-primary btn-lg')  %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align='center'> Edit User </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Avatar</th>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col"># of Articles</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |usr| %>
    <tr>
      <td><%= link_to gravatar_for(usr), user_path(usr) %>
      <td class="list-table"><%= link_to usr.username, user_path(usr) %> </td>
        <td class="list-table" ><%= usr.email %></td>
        <td class="list-table" ><%= pluralize(usr.articles.count, 'Article') %></td>
        <% if logged_in? && current_user.admin? %>
          <td class="list-table"><%= link_to 'Edit', edit_user_path(usr.id),class:'btn btn-outline-primary' %>
              <%= link_to 'Show',user_path(usr.id), class:'btn btn-outline-success'%>

                <%= link_to 'Delete', user_path(usr),class:'btn btn-outline-danger',
                    method: :delete, data: {confirm: 'are you sure you want to delete:'} %><br></td>
        
        <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1 align='center'> Sign up to Fred Blog</h1>

<%= render 'form'%>

app/views/users/show.html.erb
<h1 align='center'>Welcome to <%= @user.username %>'s page'</h1>
<div align="center">
  <%= gravatar_for @user, size: 150 %>
</div><br>
<h4 align='center'><%= @user.username %>'s article</h4>
<%= render 'articles/article', obj: @user.articles %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

<%= link_to 'home', root_path %>

app/views/welcome/index.html.erb
<div class="center jumbotron">

  <h1> Fred Blog </h2>
  <%= link_to 'Sign Up', signup_path ,class: "btn btn-primary btn-lg"%>

</div>